#!/usr/bin/env python3
import json, html
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
data=json.loads((ROOT/'data/latest.json').read_text(encoding='utf-8')) if (ROOT/'data/latest.json').exists() else {'generated_at':'هنوز اسکن انجام نشده','count':0,'top':[]}

def profile(x):
    name=(x.get('full_name') or '').lower(); text=((x.get('description') or '')+' '+name+' '+(x.get('category') or '')).lower(); cat=x.get('category') or 'سایر'
    if any(k in text for k in ('agent','llm','rag','ai','artificial intelligence','ollama','openhands')) or cat=='AI':
        return {'use':'ابزار هوش مصنوعی، ایجنت، LLM یا اتوماسیون هوشمند برای ساخت و اجرای قابلیت‌های AI.','for_you':'هسته پروژه را برای ساخت یک محصول فارسی‌زبان AI، سرویس تخصصی یا ابزار سازمانی استفاده کن.','customer':'کسب‌وکارها، تیم‌های فنی، شرکت‌ها و کاربران فارسی‌زبان.','money':'SaaS اشتراکی + API پولی + پلن Enterprise + نصب و سفارشی‌سازی.','product':'نسخه فارسی و RTL، اتصال به مدل‌های ارزان/رایگان، سرویس‌های محلی، پنل ساده و قابلیت‌های اختصاصی.','fast':'نسخه خدماتی/نصب و سفارشی‌سازی را سریع عرضه کن؛ سپس اشتراک SaaS را اضافه کن.','risk':'متوسط تا بالا'}
    if any(k in text for k in ('trading','stock','finance','crypto','investment')):
        return {'use':'تحلیل داده‌های مالی، بازار، سهام، رمزارز یا کمک به تصمیم‌گیری مالی.','for_you':'آن را به ابزار تحلیل فارسی، داشبورد بازار یا سرویس هشدار و تحلیل تبدیل کن؛ بدون وعده سود قطعی.','customer':'معامله‌گران، تحلیلگران، شرکت‌های مالی و کاربران حرفه‌ای.','money':'اشتراک ماهانه + API + گزارش حرفه‌ای + پلن سازمانی.','product':'بازار و داده فارسی، تقویم شمسی، هشدار، داشبورد و منابع داده محلی.','fast':'فروش داشبورد و گزارش تخصصی؛ بعد SaaS کامل.','risk':'بالا'}
    if any(k in text for k in ('ecommerce','commerce','shop','store','woocommerce','shopify')):
        return {'use':'ساخت یا مدیریت فروشگاه، تجارت الکترونیک، سفارش و عملیات فروش آنلاین.','for_you':'نسخه فارسی/RTL و بومی‌شده با درگاه، پیامک، مالیات و فاکتور ارائه کن.','customer':'فروشگاه‌ها، کسب‌وکارهای آنلاین و فروشندگان.','money':'اشتراک SaaS + هزینه راه‌اندازی + افزونه‌های پولی + پشتیبانی.','product':'RTL، تقویم شمسی، درگاه ایرانی، پیامک، فاکتور، حمل‌ونقل و اتصال به مارکت‌پلیس‌ها.','fast':'پکیج راه‌اندازی سریع بفروش؛ سپس سرویس اشتراکی بساز.','risk':'متوسط'}
    if any(k in text for k in ('developer','devops','docker','kubernetes','database','api','framework','testing','cli')):
        return {'use':'ابزار توسعه نرم‌افزار، زیرساخت، DevOps، API، تست یا افزایش بهره‌وری برنامه‌نویس‌ها.','for_you':'نسخه ساده‌تر، فارسی، مدیریت‌شده یا تخصصی برای یک بازار مشخص بساز.','customer':'برنامه‌نویس‌ها، تیم‌های نرم‌افزاری و شرکت‌ها.','money':'SaaS + اشتراک حرفه‌ای + پشتیبانی سازمانی + خدمات پیاده‌سازی.','product':'داشبورد فارسی، مستندات فارسی، نصب یک‌کلیکی، Cloud/Managed Service و اتصال به ابزارهای محلی.','fast':'Managed Service یا خدمات نصب بفروش؛ بعد SaaS.','risk':'متوسط'}
    if any(k in text for k in ('game','gaming','unity','godot','unreal')):
        return {'use':'ساخت بازی، موتور بازی، ابزار تولید محتوا یا زیرساخت بازی.','for_you':'ابزار یا بازی بومی، فارسی و مناسب موبایل/PC بساز و از فروش محصول و Asset درآمد بگیر.','customer':'بازیکنان، استودیوها و سازندگان بازی.','money':'فروش بازی + DLC/Asset + اشتراک ابزار + خدمات استودیویی.','product':'فارسی‌سازی، محتوای بومی، UI راست‌به‌چپ و بسته‌های آماده تولید بازی.','fast':'یک محصول کوچک قابل فروش بساز؛ سپس اکوسیستم و سرویس ایجاد کن.','risk':'متوسط'}
    return {'use':x.get('description') or 'یک پروژه متن‌باز برای حل یک مسئله نرم‌افزاری مشخص.','for_you':'از هسته پروژه برای ساخت نسخه بومی، ساده‌تر، تخصصی یا سرویس مدیریت‌شده استفاده کن.','customer':'کاربرانی که همین مسئله را دارند و برای راه‌حل آماده پول می‌دهند.','money':'نصب و سفارشی‌سازی + پشتیبانی + SaaS تخصصی.','product':'فارسی‌سازی، RTL، مستندات، رابط ساده و اتصال به سرویس‌های محلی.','fast':'ابتدا خدمات نصب/سفارشی‌سازی بفروش و پس از شناخت بازار SaaS بساز.','risk':'متوسط'}

cards=[]
for i,x in enumerate(data.get('top',[]),1):
    p=profile(x); desc=html.escape(x.get('description') or p['use']); license=html.escape(x.get('license') or 'نامشخص')
    cards.append(f'''<article class="project"><div class="rank">#{i}</div><div class="head"><div><h2><a href="{html.escape(x['url'])}" target="_blank" rel="noopener">{html.escape(x['full_name'])}</a></h2><p class="desc">{desc}</p></div><div class="score">{x['score']}<small>/100</small></div></div><div class="facts"><span>⭐ {x['stars']:,}</span><span>⚖️ {license}</span><span>🏷️ {html.escape(x.get('category') or 'سایر')}</span><span>💰 {html.escape(x.get('best_path') or p['money'])}</span></div><div class="cols"><section><h3>کاربرد پروژه</h3><p>{html.escape(p['use'])}</p></section><section><h3>کاربرد برای شما</h3><p>{html.escape(p['for_you'])}</p><p><b>مشتری هدف:</b> {html.escape(p['customer'])}</p></section><section><h3>مدل درآمدی پیشنهادی</h3><p><b>{html.escape(p['money'])}</b></p><p>{html.escape(p['product'])}</p></section><section><h3>برنامه کسب درآمد</h3><p>{html.escape(p['fast'])}</p><p>ریسک: <b>{html.escape(p['risk'])}</b></p></section></div></article>''')

html_doc=f'''<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="رادار دائمی فرصت‌های درآمدزایی از پروژه‌های متن‌باز گیت‌هاب"><title>رادار فرصت‌های درآمدی متن‌باز</title><style>*{{box-sizing:border-box}}body{{font-family:Tahoma,Arial,sans-serif;margin:0;background:#080d18;color:#e9eef8;line-height:1.8}}main{{max-width:1250px;margin:auto;padding:28px 18px}}header{{background:#111a2b;border:1px solid #263653;border-radius:20px;padding:28px;margin-bottom:20px}}h1{{margin:0 0 8px;font-size:32px}}.sub{{color:#aab7ce}}.stats{{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:20px}}.stat{{background:#18233a;padding:18px;border-radius:15px}}.stat b{{font-size:28px;display:block}}.project{{background:#111a2b;border:1px solid #263653;border-radius:18px;padding:20px;margin:16px 0}}.head{{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}}h2{{margin:0;font-size:21px}}a{{color:#8db4ff;text-decoration:none}}.desc{{color:#aab7ce;margin:5px 0}}.score{{font-size:28px;font-weight:bold;white-space:nowrap}}.score small{{font-size:13px;color:#7f8da5}}.rank{{color:#7f8da5;font-weight:bold}}.facts{{display:flex;flex-wrap:wrap;gap:10px;margin:14px 0}}.facts span{{background:#18233a;border-radius:999px;padding:5px 11px;color:#c7d2e5;font-size:13px}}.cols{{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}}section{{background:#0d1525;padding:14px;border-radius:12px}}section h3{{font-size:15px;margin:0 0 7px;color:#dbe7ff}}section p{{margin:4px 0;color:#b8c4d8;font-size:14px}}.note{{color:#8796ae;font-size:12px;margin-top:20px}}@media(max-width:900px){{.cols{{grid-template-columns:repeat(2,1fr)}}}}@media(max-width:600px){{.stats,.cols{{grid-template-columns:1fr}}.head{{display:block}}.score{{margin-top:10px}}}}</style></head><body><main><header><h1>📡 رادار فرصت‌های درآمدی متن‌باز</h1><div class="sub">تحلیل هر پروژه: کاربرد واقعی، کاربرد برای شما، مشتری هدف، محصول قابل ساخت، مدل درآمدی و مسیر شروع.</div><div class="stats"><div class="stat"><b>{data.get('count',0)}</b>پروژه اسکن‌شده</div><div class="stat"><b>{len(data.get('top',[]))}</b>فرصت رتبه‌بندی‌شده</div><div class="stat"><b>روزانه</b>اسکن خودکار</div></div><div class="sub">آخرین بروزرسانی: {html.escape(data.get('generated_at',''))}</div></header><h1>🏆 فرصت‌های برتر</h1>{''.join(cards)}<p class="note">تحلیل کسب‌وکار یک فرضیه است، نه تضمین درآمد. پیش از استفاده تجاری، LICENSE، NOTICE، وابستگی‌ها و علائم تجاری پروژه بررسی شوند.</p></main></body></html>'''
out=ROOT/'dashboard'/'index.html';out.parent.mkdir(exist_ok=True);out.write_text(html_doc,encoding='utf-8')
